### PR TITLE
ARCH-1867 - fix handling of unicode characters in resource repr

### PR DESCRIPTION
**Pull request by mcordes**
Return non-unicode string from \_\_repr__ methods for py2 and unicode string for py3.

### CODE REVIEW

**Comment by mcordes** [comment]
Here's an example of how repr works with python2:

    >>> class foo(object):
    ...     def __repr__(self):
    ...         return "foo"
    ... 
    >>>  
    >>> class unicodefoo(object):
    ...     def __repr__(self):
    ...         return u"J'aurais adoré être"
    ... 
    >>> 
    >>> foo()
    foo
    >>> unicodefoo()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
     UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 13: ordinal not in range(128)
    >>>

**Comment by mpistrang** [comment]
I see that this project still has __unicode__ methods defined.  I'm under the impression that python3 will not look for this method, so do you plan on bringing Nap closer to python3 in the future as well?

**Comment by mcordes** [comment]
@mpistrang 
My intention was just to fix the repr errors and not worry about the \_\_unicode\_\_ methods for right now. I'd like to get this into 8.06 onboarding with minimal changes.  

Also, the django proposed method for dealing with \_\_str\_\_ vs \_\_unicode\_\_ isn't going to work here b/c nap doesn't depend on django. 

You're right that py2 will do stuff (although what exactly, I don't understand yet) with the \_\_unicode\_\_ and py3 won't, but I don't think that's a big deal. Do you?

**Comment by mcordes** [comment]
I got it:

py2:

\_\_repr\_\_ - called by repr(thing)
\_\_unicode\_\_ - called by unicode(thing)
\_\_str\_\_ - called by str(thing) - has to be raw string, not unicode string

py3:

\_\_repr\_\_ - ditto 
\_\_unicode\_\_ - ignored
\_\_str\_\_ - called by str(thing) - has to be unicode string (not bytestring)

So to me \_\_str\_\_ is the dangerous one b/c it changes the behavior between py2 and py3.

**Comment by mpistrang** [comment]
The django proposed method really just calls six.python_2_unicode_compatible.

**Comment by mcordes** [comment]
@mpistrang 

Awesome, I didn't realize that. Ok, I'll add that too.

**Comment by mcordes** [comment]
I take that back, let's do that in 8.06. I think making that change will require changing too many nap clients for 8.06 onboarding. I imagine I'll need to change nap's resource to use the decorator and rename \_\_unicode\_\_ to \_\_str\_\_ and then rename all the overridden \_\_unicode\_\_ methods in the various subclasses in multiple client packages.

**Pull request merged**
